### ISSUE TITLE
Travis Badge Points to Wrong Repo

### ISSUE THREAD

**Issue by sunnyrjuneja** [sunlightlabs/ruby-sunlight#15]
The Travis Badge is pointing to: https://travis-ci.org/nihonjinrxs/ruby-sunlight
Someone with write access needs to add sunlightlabs/ruby-sunlight to travis.

**Comment by konklone** [comment]
I just removed the badge links entirely, thanks for pointing them out. We'll re-add badges depending on what we do this repo.
