### ISSUE TITLE
uninitialized constant PeopleController::Lobbyist

### ISSUE THREAD

**Issue by yoshie902a** [sunlightlabs/ruby-sunlight#6]
In your example, you have

```
lobbyists = Lobbyist.search("Nisha Thompsen")
lobbyists =Lobbyist.search("Michael Klein", 0.95, 2007)     
```

I believe it should be....

```
    lobbyists = Sunlight::Lobbyist.search("Nisha Thompsen")
lobbyists = Sunlight::Lobbyist.search("Michael Klein", 0.95, 2007)  
```

....
Update:  I just tried Sunlight::Lobbyist.search and still get uninitialized constant PeopleController::Lobbyist.
Any ideas?

**Comment by konklone** [comment]
We pulled that code out of the library, and apparently neglected to update the documentation to reflect that. That refers to an older, unsupported API. I'm updating the docs now to remove references to it.
