### ISSUE TITLE
Update test coverage framework to support Ruby 1.9 and 2.x.

### ISSUE THREAD

**Issue by nihonjinrxs** [sunlightlabs/ruby-sunlight#8]
The `rcov` gem is deprecated as of 1.9, and a move to `simplecov` is recommended.  We need to move this gem to support `rcov` on 1.8 and below and `simplecov` on 1.9 and above.

**Comment by nihonjinrxs** [comment]
I should be able to take this one on.  I'll hopefully have a pull request for you by this weekend.

**Comment by konklone** [comment]
I appreciate you breathing life into this gem. If you file a pull request, I'll consider it sufficient nudge to get this gem working with our new API next week. Thanks for doing this.

**Comment by konklone** [comment]
Fixed by #10.
