### ISSUE TITLE
Test failure: nil returned, possibly Geocoding not found?

### ISSUE THREAD

**Issue by nihonjinrxs** [sunlightlabs/ruby-sunlight#9]
Started looking at this gem, and ran the test suite (via `rake` at the zsh prompt).  Got one failure, which looks to be because it can't find the `Geocoding` module.

```
...
Failures:

  1) Sunlight::Legislator#all_for should return hash when valid address is passed in
     Failure/Error: legislators = Sunlight::Legislator.all_for(:address => "123 Fake St Anytown USA")
     NoMethodError:
       undefined method `text' for nil:NilClass
     # ./lib/sunlight/district.rb:26:in `get'
     # ./lib/sunlight/legislator.rb:71:in `all_for'
     # ./spec/legislator_spec.rb:91:in `block (3 levels) in <top (required)>'

Finished in 0.2621 seconds
41 examples, 1 failure
rake aborted!
ruby -S bundle exec rspec --colour --format documentation spec/base_spec.rb spec/committee_spec.rb spec/district_spec.rb spec/legislator_spec.rb failed
```

Looking at `./lib/sunlight/district.rb:26`:

``` ruby
placemarks = Geocoding::get(params[:address])
```

I can't find any other reference to `Geocoding` in the project.  Any ideas here?

**Comment by konklone** [comment]
Man, this gem really needs some work. It's been fallow for a while. There's a rework in progress in a branch to use the new [Congress API](http://sunlightlabs.github.io/congress/).

We'll work on that, but if you just need something to work in the meantime, try checking out @sferik's [congress gem](http://rubygems.org/gems/congress). In the meantime, I'm going to close this, as this affects the gem's use of a deprecated API.

**Comment by sferik** [comment]
Is there a good reason to maintain both this project and the `congress` gem? It seems like unnecessary duplication of effort.

**Comment by konklone** [comment]
That's a fair point. What I really don't want is a dead or broken gem. So we should either kill it, or fix it for the new API. The best reason we'd have for keeping a `sunlight` gem around would be if we take it the way of our [python-sunlight](http://python-sunlight.readthedocs.org/en/latest/) library, which connects a bunch of our APIs together in one place. It's a nice approach for a lot of people. Even then, we could possibly have it include the `congress` gem as a dependency and use it that way. 

Anyway, if you can't tell, we haven't thought this out fully. I'm just reacting to the feeling of having public broken code.

**Comment by nihonjinrxs** [comment]
I personally like the idea of having a single `sunlight` gem that connects a bunch of the APIs together.  I'm happy to do some work on it when I have time (can't guarantee anything, but I'll do my best).  I also think it's a great idea to use the `congress` gem if it's being well maintained.  My goal with the issues was to note that it was in bad shape and try to help out some.
